import { type Session } from "next-auth";
import SessionProviderWrapper from "~/component/SessionProviderWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session
}) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper session={session}>
        {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
